# generated by datamodel-codegen:
#   filename:  openapi.v1.json

from __future__ import annotations

from enum import Enum
from typing import Literal, Optional

from pydantic import (
    AnyUrl,
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    RootModel,
    conint,
    constr,
)


class Error(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: constr(pattern=r"^[a-z][a-z0-9_]{0,79}$", max_length=80) = Field(
        ..., description="Stable machine-readable error code."
    )
    message: constr(min_length=1, max_length=500)
    request_id: constr(min_length=1, max_length=128)
    details: Optional[dict[str, constr(max_length=256)]] = Field(
        None,
        description="Optional bounded diagnostic values. Clients must branch on code, not message or detail text.",
    )


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    error: Error


class SoulId(
    RootModel[
        constr(
            pattern=r"^soul_[A-Za-z0-9][A-Za-z0-9._:-]{0,126}$",
            min_length=1,
            max_length=128,
        )
    ]
):
    root: constr(
        pattern=r"^soul_[A-Za-z0-9][A-Za-z0-9._:-]{0,126}$",
        min_length=1,
        max_length=128,
    ) = Field(..., description="Opaque company-scoped Soul identifier.")


class OperationId(
    RootModel[
        constr(
            pattern=r"^op_[A-Za-z0-9][A-Za-z0-9._:-]{0,126}$",
            min_length=1,
            max_length=128,
        )
    ]
):
    root: constr(
        pattern=r"^op_[A-Za-z0-9][A-Za-z0-9._:-]{0,126}$", min_length=1, max_length=128
    ) = Field(..., description="Opaque company-scoped operation identifier.")


class SourceAssetId(
    RootModel[
        constr(
            pattern=r"^ssa_[A-Za-z0-9][A-Za-z0-9._:-]{0,126}$",
            min_length=1,
            max_length=128,
        )
    ]
):
    root: constr(
        pattern=r"^ssa_[A-Za-z0-9][A-Za-z0-9._:-]{0,126}$", min_length=1, max_length=128
    ) = Field(..., description="Opaque company-scoped source-asset identifier.")


class ExternalSoulId(
    RootModel[
        constr(
            pattern=r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", min_length=1, max_length=128
        )
    ]
):
    root: constr(
        pattern=r"^[A-Za-z0-9][A-Za-z0-9._:-]{0,127}$", min_length=1, max_length=128
    ) = Field(
        ...,
        description="Stable identifier chosen by the partner within its company scope.",
    )


class SoulKind(Enum):
    human = "human"
    creature = "creature"


class SourceAssetType(Enum):
    appearance_reference = "appearance_reference"
    content_style_reference = "content_style_reference"
    text_video_timeline = "text_video_timeline"


class Lifecycle(Enum):
    draft = "draft"
    active = "active"
    suspended = "suspended"
    deleted = "deleted"


class MediaDeclaration(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    content_type: constr(
        pattern=r"^[A-Za-z0-9!#$&^_.+-]+/[A-Za-z0-9!#$&^_.+-]+$",
        min_length=1,
        max_length=128,
    )
    byte_length: conint(ge=1, le=5000000000)
    sha256: constr(pattern=r"^[a-f0-9]{64}$", min_length=64, max_length=64)


class Basis(Enum):
    owned_or_licensed = "owned_or_licensed"


class RightsAttestation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    basis: Basis
    subject_consent: bool


class TimelineAnnotation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    request_at_ms: conint(ge=0, le=86400000)
    behavior_start_ms: conint(ge=0, le=86400000)
    behavior_end_ms: conint(ge=1, le=86400000)
    user_request: constr(min_length=1, max_length=2000)


class SourceAssetCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: SourceAssetType
    media: MediaDeclaration
    annotations: Optional[list[TimelineAnnotation]] = Field(
        None,
        description="Required only for text_video_timeline; annotations must be ordered, in-bounds, and non-overlapping.",
        max_length=128,
        min_length=1,
    )
    rights_attestation: RightsAttestation


class UploadTarget(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    method: Literal["PUT"]
    url: AnyUrl
    expires_at: AwareDatetime
    headers: Optional[dict[str, constr(max_length=512)]] = Field(
        None,
        description="Optional bounded headers required by the direct-upload target.",
    )


class SourceAssetStatus(Enum):
    upload_pending = "upload_pending"
    validating = "validating"
    ready = "ready"
    rejected = "rejected"
    expired = "expired"


class SourceAsset(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_asset_id: SourceAssetId
    type: SourceAssetType
    status: SourceAssetStatus
    media: MediaDeclaration
    annotations: Optional[list[TimelineAnnotation]] = Field(None, max_length=128)
    rights_attestation: RightsAttestation
    upload: UploadTarget
    created_at: AwareDatetime


class SoulCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    external_soul_id: ExternalSoulId
    kind: SoulKind
    description: constr(min_length=1, max_length=4000)
    source_asset_ids: list[SourceAssetId] = Field(
        ...,
        description="Ordered, immutable source-asset manifest. Use an empty array for description-only creation.",
        max_length=16,
        min_length=0,
    )


class SoulUpdateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    expected_revision: conint(ge=1, le=2147483647)
    description: Optional[constr(min_length=1, max_length=4000)] = None


class SoulCapabilities(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    responses: bool
    image_generation: bool
    video_generation: bool


class Soul(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    soul_id: SoulId
    external_soul_id: ExternalSoulId
    kind: SoulKind
    description: constr(min_length=1, max_length=4000)
    lifecycle: Lifecycle
    revision: conint(ge=1, le=2147483647)
    source_asset_ids: list[SourceAssetId] = Field(..., max_length=16)
    capabilities: SoulCapabilities
    created_at: AwareDatetime
    updated_at: AwareDatetime


class Role(Enum):
    user = "user"
    assistant = "assistant"


class ConversationMessage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Role
    content: constr(min_length=1, max_length=8000)


class ResponseCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    messages: list[ConversationMessage] = Field(
        ...,
        description="Ordered, bounded conversation context supplied by the partner.",
        max_length=64,
        min_length=1,
    )
    max_output_tokens: Optional[conint(ge=1, le=2048)] = None


class QuoteReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    quote_id: constr(min_length=1, max_length=128)


class Kind(Enum):
    image = "image"
    video = "video"


class GenerationCreateRequest(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind
    prompt: constr(min_length=1, max_length=4000)
    quote_id: constr(min_length=1, max_length=128) = Field(
        ...,
        description="Opaque server-issued quote identifier; clients do not calculate Gem amounts.",
    )
    duration_ms: Optional[conint(ge=1000, le=120000)] = Field(
        None,
        description="Requested video duration. Required for video and ignored for image only when the server explicitly documents that behavior.",
    )
    source_asset_ids: Optional[list[SourceAssetId]] = Field(None, max_length=8)


class Type(Enum):
    source_asset = "source_asset"
    soul = "soul"
    response = "response"
    generation = "generation"


class ResourceReference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: Type
    id: constr(min_length=1, max_length=128)


class OperationKind(Enum):
    source_asset_validation = "source_asset_validation"
    soul_creation = "soul_creation"
    soul_update = "soul_update"
    soul_response = "soul_response"
    image_generation = "image_generation"
    video_generation = "video_generation"


class OperationStatus(Enum):
    accepted = "accepted"
    submitted = "submitted"
    running = "running"
    acceptance_unknown = "acceptance_unknown"
    succeeded = "succeeded"
    failed = "failed"
    canceled = "canceled"


class OperationFailure(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: constr(pattern=r"^[a-z][a-z0-9_]{0,79}$", max_length=80)
    message: constr(min_length=1, max_length=500)
    retryable: bool


class OperationUsage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    reserved_gems: conint(ge=0, le=1000000000)
    consumed_gems: conint(ge=0, le=1000000000)
    released_gems: conint(ge=0, le=1000000000)


class MediaLocator(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind
    url: AnyUrl
    expires_at: AwareDatetime


class Kind2(Enum):
    text = "text"
    image = "image"
    video = "video"


class OperationOutput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind2
    text: Optional[constr(min_length=1, max_length=20000)] = None
    media: Optional[list[MediaLocator]] = Field(None, max_length=8)


class OperationLinks(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    self: AnyUrl


class Operation(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation_id: OperationId
    kind: OperationKind
    status: OperationStatus
    resource: Optional[ResourceReference] = None
    progress_percent: Optional[conint(ge=0, le=100)] = None
    quote: Optional[QuoteReference] = None
    usage: Optional[OperationUsage] = None
    failure: Optional[OperationFailure] = None
    output: Optional[OperationOutput] = None
    created_at: AwareDatetime
    updated_at: AwareDatetime
    links: Optional[OperationLinks] = None


class OperationAcceptedResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    operation: Operation


class SourceAssetAcceptedResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source_asset: SourceAsset
    operation: Operation


class SoulAcceptedResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    soul: Soul
    operation: Operation


class SoulUpdateAcceptedResponse(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    soul: Soul
    operation: Operation
